### ISSUE TITLE
README.md - mistake in usage example

### ISSUE THREAD

**Issue by templar1** [opensoft/doctrine-postgres-types#11]
In README file there is small issue in usage with symfony.

There is:
```
tsvector: "Doctrine\\DBAL\\PostgresTypes\\TsvectorType"
tsquery: "Doctrine\\DBAL\\PostgresTypes\\TsqueryType"
```

And should be:
```
ts_vector: "Doctrine\\DBAL\\PostgresTypes\\TsvectorType"
ts_query: "Doctrine\\DBAL\\PostgresTypes\\TsqueryType"
```

**Comment by richardfullmer** [comment]
As far as I know, these are arbitrary, right?  You can name and use them however you'd like.

**Comment by templar1** [comment]
There is no consistency in documentation. You can name it however you want but names in "types" and "mapping_tapes" should be the same.

So if we name type as "tsvector" then in mapping_type should be "tsvector: tsvector"

**Comment by richardfullmer** [comment]
Agreed.  Fixed
