### ISSUE TITLE
Maybe it would be nice to get a new stable version 1.*

### ISSUE THREAD

**Issue by grizzlylab** [opensoft/doctrine-postgres-types#9]
Hi, is it possible to define a new stable version ? 
Because some "types" are missing in the last stable version ;)
So I must use "dev-master" wich SensioLabs Insight and me doesn't like very much :cry:

**Comment by richardfullmer** [comment]
I can easily tag the current master branch as 1.0.0.  It doesn't have to have every type under the sun to be tagged.

**Comment by richardfullmer** [comment]
Tagged latest as 1.2.0
